name: Build Nuxt and Docker

on:
  push:
    branches:
      - main

jobs:
  build-nuxt:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./src


    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ${{env.working-directory}}

      - name: Build Nuxt
        run: npx nuxi build
        working-directory: ${{env.working-directory}}
          
      - name: List .output
        run: ls -R ${{env.working-directory}}/.output
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: nuxt
          # Directory containing files to upload
          path: ${{env.working-directory}}/.output
          # Days before delete
          retention-days: 1

  build-docker-nuxt:

    needs: [build-nuxt]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nuxt
          path: nuxt
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/nuxt:latest
      
